/*

 GAMEPLAYGUI.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Business\LaroldsJubilantJunkyard\tetris\gui.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 13
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define GameplayGuiWidth 20
#define GameplayGuiHeight 18
#define GameplayGuiBank 0

extern unsigned char GameplayGui[];

/* End of GAMEPLAYGUI.H */
