/*

 BARRICADEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 4
   Tile set      : D:\Business\LaroldsJubilantJunkyard\game remakes\space-invaders\SpaceInvadersTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BarricadeMapWidth 5
#define BarricadeMapHeight 4
#define BarricadeMapBank 0

extern unsigned char BarricadeMap[];

/* End of BARRICADEMAP.H */
